version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    platform: linux/amd64
    restart: always
    environment:
      TZ: Asia/Bangkok                # ตั้ง timezone ของ container
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql        # เก็บ data
      - ./mysql/conf.d:/etc/mysql/conf.d   # โหลดไฟล์ config เสริม (my.cnf)
      - /etc/localtime:/etc/localtime:ro   # sync เวลาโฮสต์ -> container
      - /etc/timezone:/etc/timezone:ro

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    platform: linux/amd64
    restart: always
    ports:
      - "8080:80"
    environment:
      TZ: Asia/Bangkok
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: rootpass
      UPLOAD_LIMIT: 1024M
      MEMORY_LIMIT: 1024M
    depends_on:
      - db


volumes:
  db_data:
